### ISSUE TITLE
Install removed the msql password

### ISSUE THREAD

**Issue by StormTrooper** [fdietz/team_dashboard#105]
Running OpenSuse 12.3 - when I installed team_dashboard, it removed the mysql password I had setup on my DB's

Maybe the docs need to be updated to refer to this:

database.yml:
default: &mysql
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password:

**Comment by fdietz** [comment]
Hi!

can you please elaborate what you mean by "installed" team_dashboard.

The readme file explains how to do the following to create an initial database.yml file:
cp config/database.example.yml config/database.yml

Cheers,
Frederik

**Comment by StormTrooper** [comment]
Hi there,
Well not really installed, I followed the instructions and copied the file, but I I just wanted to let you know that the script removed the password from an already running mysql server.
RegardsGreg

Date: Mon, 2 Sep 2013 11:15:12 -0700

**Comment by fdietz** [comment]
Hi again,

thanks for your quick response. Then its probably sufficient to add a hint
to the copy statement that this overrides your existing settings.

Thanks!
Frederik

**Comment by StormTrooper** [comment]
Thanks - I think that would be great.

Date: Mon, 2 Sep 2013 11:34:15 -0700
