### ISSUE TITLE
Please name the Prerequisites packages needed when using bundle

### ISSUE THREAD

**Issue by laapsaap** [fdietz/team_dashboard#106]
Ruby Gem + Bundle is every system administrator worst nightmare.  The pain would be less if I had a list of Prerequisites I need to install before running `bundle install`

now it is run `bundle install` wait till it fails and look what is missing etc.

I have doing this 6-7 times right now and still missing packages.

**Comment by fdietz** [comment]
I don't have a list of dependencies and sadly don't have the resources to support an "installer" or "packages" for various operating systems.

And of course this depends on the platform. Which platform are you using?

For example for linux to get ruby and rails installed you have to start with the following packages:

sudo apt-get install build-essential openssl libreadline6 libreadline6-dev \
curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 \
libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison  \
subversion pkg-config

For a development setup, I can recommend the following article as a starter:
http://coding.smashingmagazine.com/2011/06/21/set-up-an-ubuntu-local-development-machine-for-ruby-on-rails/

I'd love to add some more information to the readme when you managed to get it working for you!

Cheers,
Frederik

**Comment by fdietz** [comment]
Fixed https://github.com/fdietz/team_dashboard/commit/7dbe2d39c2e60ef11e1b2e22ea9142e3cec2d126
