### ISSUE TITLE
There are examples of stacked graphs widgets, but those arent really "stacked"

### ISSUE THREAD

**Issue by laapsaap** [fdietz/team_dashboard#110]
Hi,

There are examples of stacked graphs widgets, but those arent really "stacked". Just an overlay of two graphs.  When we are talking about stacked area graphs, it should be added up.

**Comment by fdietz** [comment]
Hi again,

this is correct, the current version of the graph widget does not support
stacking.

The old rendering engine was based on a different library, but had other
issues. I hope that we can mid term use the old rendering engine again
though!

Cheers,
Frederik

**Comment by fdietz** [comment]
I renamed "stacked" to "area" graph in the populate.rake task
