### ISSUE TITLE
Graphite link failed

### ISSUE THREAD

**Issue by guizello** [fdietz/team_dashboard#125]
Hello,

I'm trying to link the dashboard to Graphite. Variable has been exported and i force it when i launch rails but i got this issue that i don't understand: 

```
Internal Server Error: #<NoMethodError: undefined method `datapoints_svg_url' for nil:NilClass> 
```

Maybe could you help,
Thank you

**Comment by fdietz** [comment]
Fixed on master. Thanks!

**Comment by guizello** [comment]
Hello again, sorry to reopen this but i got now this error : 

![screen shot 2014-02-24 at 11 07 39](https://f.cloud.github.com/assets/5029347/2244288/ad640f58-9d3b-11e3-986f-fad1a6bcbf20.png)

Can you help ?

Thank you again.

**Comment by fdietz** [comment]
Hi again,

this is a an error trace from graphite web, so it might not even be related
to a problem in team dashboard.

Note, that the production.log file contains the http request url done to
graphite web. You can easily take that and try it for yourself with your
web browser.

Cheers,
Frederik

**Comment by guizello** [comment]
Great thanks I'm gonna read it. 

Regards,
Guillaume
