### ISSUE TITLE
can't run unit test - ActiveRecord::StatementInvalid: Could not find table 'widgets'

### ISSUE THREAD

**Issue by leifhanack** [fdietz/team_dashboard#127]
hi there, 

i cloned your repo but get errors when running some specs. 
test case is e.g. "#get returns a hash":

```
ActiveRecord::StatementInvalid: Could not find table 'widgets'
./spec/models/sources/ci/jenkins_spec.rb:8:in `block (2 levels) in <top (required)>'
./spec/models/sources/ci/jenkins_spec.rb:15:in `block (3 levels) in <top (required)>'
```

i'm totally new to ruby so i'm not sure if i missed some setup. it seems as if mocking of the widget does not work as expected.

do you have some advice?

regards, leif

**Comment by fdietz** [comment]
Hi Leif,

it seems that the test DB was not created.

Have you run "rake db:migrate" and "rake db:test:prepare"? Check if there's
a database "team_dashboard_test" which should contains all the tables as
listed in schema.rb.

Cheers,
Frederik

**Comment by leifhanack** [comment]
Ah, I see. 

No, I tried to run it from within IntellijIdea by "right-clicking". 

I'm writing a Teamcity CI provider and tend to mock the DB stuff. Is this wise? I guess it's somewhere else tested that a widget is working. If I mock widget I can concentrate on testing the provider functionality. What do you think?

Regards, Leif

**Comment by fdietz** [comment]
You can certainly mock the db layer in your test. Have a look at the
existing tests.

**Comment by leifhanack** [comment]
Sorry for being such a ruby noob. My first ruby code I saw is yours:)

If I take a look at Sources::Ci::Travis I see:

```
def get(options = {})
  widget = Widget.find(options.fetch(:widget_id))
  ..
end
```

I would like to mock that call on the active record so that I don't need a running database. 

I tried s.th. like this

```
    before(:each) do
      @widget = mock(Widget)
    end

    it "returns a hash" do
      @widget.should_receive(:find).and_return(my_widget_mock)
    end
```

which results in `TypeError: Widget(Table doesn't exist) is not a symbol` at `mock(Widget)`.

Could you assist me a bit? 
Thanks a lot, Leif

**Comment by fdietz** [comment]
Hi again,

Here's the best rspec doc I've found describing the various concepts in
Rails:
https://www.relishapp.com/rspec/rspec-rails/v/2-0/docs/mocks/mock-model

Note, that you still have the "Table doesn't exist" error. So, please make
sure you follow the README. Create a database.yml and execute rake
db:migrate and run rake once to check if the other tests work.

Cheers,
Frederik

**Comment by leifhanack** [comment]
Hi Frederik, 
I was able to run all tests. 

But writing my own spec and mock out Widget didn't work as expected. Finally I found the reason. Inside your spec_helper.rb you are using mocha for mocking. It seems as if mocha didn't support mock_model. Now I know where to dig and that I have to use s.th. like:

```
describe "test without db" do
    it "find should return widget" do
      widget = Widget.new
      Widget.expects(:find).returns(widget)

      myModule.get(12)

    end
  end
```

Regards, Leif
