### ISSUE TITLE
Graph widget support for Graphite constantLine, drawAsInfinite, events functions 

### ISSUE THREAD

**Issue by fdietz** [fdietz/team_dashboard#21]
All these functions return a datapoints array which doesn't match a request graph target. Whereas the graph has datapoints for each timestamp, the constantLine has only a single datapoint. 

rickshaw.js can't handle that and throws the following error message :

Uncaught series cannot have differing numbers of points: 60 vs 1; see Rickshaw.Series.zeroFill() 

(this happens in the this.validateSeries() function, before even trying to render the graph)

So we have to either adapt the datapoints json on the server or client side. Client side would be nicer since it keeps the data source plugins simple. It might be possible that its actually cleaner to support specific things, like a horizontal or vertical line in the graph (as an overlay) explicitly on the server side though.

**Comment by tubit** [comment]
I would love to see drawAsInfinite working. We're using drawAsInfinite for drawing "events" metrics in our graphs.

e.g. if someone is doing a cms publish a "1" is send to graphite as metric "foo.cms_publish". In our webserver response graph this metric is shown as "drawAsInfinite(foo.cms_publish)".

**Comment by fdietz** [comment]
I'm planning a change in direction here, since I'm not confident that we get the graphing library to work and graphite-web providing all required information in their json api. 

We are going to use the svg generated graph supported in more recent graphite-web versions. That way we can render the graph as returned by graphite-web as is. 

I've created a new ticket for start and work will start right after the version 2 final release:
https://github.com/fdietz/team_dashboard/issues/80

I consider this issue therefore closed.
