### ISSUE TITLE
upgrade to Rails 3.2.8 breaks drag/drop for widgets

### ISSUE THREAD

**Issue by cleesmith** [fdietz/team_dashboard#29]
Doing a git clone and following the "Getting Started" works/looks great ... thanks.

But doing an upgrade of Rails to 3.2.8 breaks the UI drag/drop for widgets as follows:

gem 'rails', '3.2.8'  <- in Gemfile
 Bundler could not find compatible versions for gem "activesupport":
   In snapshot (Gemfile.lock):
     activesupport (3.2.5)
   In Gemfile:
     rails (= 3.2.8) ruby depends on
       activesupport (= 3.2.8) ruby
 Running `bundle update` will rebuild your snapshot from scratch, using only
 the gems in your Gemfile, which may resolve the conflict.

... so after doing a 'bundle update' ... the following error in Chrome's developer console appears 
after any attempt to do a drag/drop on a widget:

```
Uncaught TypeError: Object function ( selector, context ) {
  // The jQuery object is actually just the init constructor 'enhanced'
  return new jQuery.fn.init( selector, context, rootjQuery );
} has no method 'curCSS'
jquery-ui-1.8.20.custom.min.js:6
```

Any suggestions on how to fix ?
Thanks

**Comment by fdietz** [comment]
Hi,

the jquery-ui version didn't match your jquery version after the "bundle update" (which implicitly updated rails-jquery).

I've updated jquery-ui and added some more strict versions into the Gemfile.

Thanks!
-Frederik
