### ISSUE TITLE
Widgets now have white background

### ISSUE THREAD

**Issue by leifg** [fdietz/team_dashboard#31]
I recently pulled the latest changes from the repo and now all my widgets look extremely ugly (the background of each widget is white, which doesn't fit the dashboard at all).

I assume this got in with the following commit:

https://github.com/fdietz/team_dashboard/commit/5850981cbf995d203427bebfb6e75fb5fc447598

```
-    className: "widget",
+    className: "widget portlet well well-small ui-widget ui-widget-content ui-corner-all",
```

The class `well` is defined in twitter boostrap with:

  background-color: #f5f5f5; (pretty much white)

so I think this class needs to be overwritten or removed from the widget div

**Comment by fdietz** [comment]
Hi Leif,

I can't reproduce this with the latest version. Can you give this another
try with the latest version and bundle install, please?

I've had this problem when updating gems, specifically twitter bootstrap
but I've fixed it:
https://github.com/fdietz/team_dashboard/commit/ec13a14be83df5624481684d9ab72d24c9c4c4fd

Additionally, I've ensured that such an update can't happen again here:
https://github.com/fdietz/team_dashboard/commit/7510c410f9d9d259f7b44a1b760eed224da280a0

The "well" class is defined as you describe, but I'm using a custom twitter
bootstrap theme:

.well, .hero-unit {
  border-top: solid 1px lighten(@grayDark, 5%);
  .box-shadow(0 2px 4px rgba(0,0,0,.8));
}

So, somehow on your local version the theme is not loaded correctly, I
assume

Kind regards,
-Frederik

**Comment by leifg** [comment]
no chance... 100% reproducible on my side. I deleted the folder and cloned again, I used it via ´bundle install --path vendor/local´

I also tried installing the gems into the system. Nothing changed.

The index.css looks like this, and according to chrome web-inspector the background-color: #f5f5f5; is aplied. 

```
.well {
  min-height: 20px;
  padding: 19px;
  margin-bottom: 20px;
  background-color: #f5f5f5;
  border: 1px solid #eee;
  border: 1px solid rgba(0, 0, 0, 0.05);
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}
```

**Comment by fdietz** [comment]
Hi again,

this is what my version if index.css returns:

```
.well {
  min-height: 20px;
  padding: 19px;
  margin-bottom: 20px;
  background-color: #131517;
  border: 1px solid #030303;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}
```

I've tried again with a fresh checkout, bundle install and it works for me. It also works on our live system.

Can you try do clear your browser cache, please?

Also, take a look into application.css, since it includes the require to theme/index.less which imports bootswatch.less and variables.less (the actual customized theme). Try to change things and see if your browser reflects these changes properly. The development.log will show your errors in case less can't compile to css correctly. You could even try to do a full compile to a single application.css by changing the "config.assets.debug = true" to false in your development.rb.

**Comment by leifg** [comment]
OK this one can be closed. 

Reloaded again and now now it works, thanks though for your effort.

**Comment by michaelwalters** [comment]
There is definitely an issue here.  I installed and ran this app and saw that it had a black background, but later after a 'bundle update' & 'bundle install', I get the white background.

This issue is definitely related to bootswatch.  For some reason, the default theme is being used.
