### ISSUE TITLE
Possibility of having Alert Widgets

### ISSUE THREAD

**Issue by DraganMileski** [fdietz/team_dashboard#37]
The dashboard might become a little bit inefficient when it is used for big and complex systems where a lot of data has to be monitored. Sometimes even very big screen wont be enough to put all checks that you want. Even if you can put all of them it takes time to check them one by one whether everything is going well. One nice idea could be: 
- Monitoring only what you need in the moment and show an alert view widget on the first place of the screen when something goes wrong even if you dont have it on the current dashboard configuration. 

For example if the server disk space goes above the predefined threshold and you dont have it on your dashboard, you definitely want to know it right away.

**Comment by fdietz** [comment]
1. You could achieve something close with just using a boolean widget (showing a red status), but of course you need the data source plugin for whatever you use as alert system (nagios, etc.).
2. Another option would be to add a widget which specifically raises alerts from a given very large system - something like the first page of the nagios web frontend.
3. User's first reaction is of course that Team Dashboard should support setting Thresholds and sending alerts, too. But, I  guess that is a bit too much for my short term goals. I need to focus on just the dashboard widgets for some time to really polish everything.

So, I guess 1) can already be done today. 2) would be just another widget implementation, which can be done easily. 3) is too far away currently for me.

Your suggestion to have alerts come up, independently of the dashboard currently shown is more something I'd group in 3) for now. 

That said I definitely see this whole business of alerts as a first class concept for the future development of Team Dashboard.
