### ISSUE TITLE
SSL certificate verification issue

### ISSUE THREAD

**Issue by rngtng** [fdietz/team_dashboard#50]
I have an issue with SSL certificate verification. Looks like it's not valid (enough) and so I want to disable the verification (for now). I only could solve this by adding to various places:

```
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
```

or

```
::HttpService.request(url, :ssl => {:verify => false})
```

Any chance or ideas how to configure this globally? Sth. like default `HttpService`  params??

**Comment by fdietz** [comment]
The whole reasoning behind HttpService as the single way for all widget http requests is to have a single place to configure everything.

Use Faraday.default_connection_options to set default options, most probably inside a rails config/initializer. 

Another option would be to use a config/initializer to set the following:
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

This might be ok in your case depending your what your site ops handle security. More information about SSL and faraday can be found here:
https://github.com/technoweenie/faraday/wiki/Setting-up-SSL-certificates

Note, that when setting these in the config/initializer in your git clone you make it super easy to pull changes from upstream.

**Comment by rngtng** [comment]
oh yeah cool - thx! I'll give it a try..

**Comment by rngtng** [comment]
Ok I gave it a try, unfortunately `Faraday.default_connection_options` is not part of Faraday 0.8.4 version. So it needs wait until v0.9 is released. But `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE` did indeed the trick (for now) - thx.
