### ISSUE TITLE
Icinga-Web and Number Widget

### ISSUE THREAD

**Issue by tubit** [fdietz/team_dashboard#53]
Hi,

I try to integrate our icinga installation to team dashboard. icinga-web provides a neat api interface with json output.

The URI scheme is like
http://hostname/icinga-web/api/ %TARGET% / %COLUMNS% / %FILTER% / %ORDER% / %GROUPING% / %LIMIT% / %COUNTFIELD% / %OUTPUT_TYPE%

A filter is build like:
filters[AND(%column%|%operator%|%value%;%column%|%operator%|%value%)] 

So a URI to get all Host in State 1 (down) is:

http://hostname/icinga-web/web/api/host/filter[AND(HOST_CURRENT_STATE%7C=%7C1)]/countColumn=COL/authkey=MYKEY/json

The output is something like:
{"result":[{"HOST_ID":"198616","HOST_OBJECT_ID":"2050","HOST_INSTANCE_ID":"1","HOST_NAME":"host.fooo","HOST_ALIAS":"host_alias","HOST_DISPLAY_NAME":"host.foo","HOST_ADDRESS":"172.0.0.123","HOST_IS_ACTIVE":"1"}],"success":"true","total":1}

But if I paste those URI to the http_proxy_url in a Number Widget, I just get the following error:
Error loading datapoints:

Internal server error: bad URI(is not URI?): http://hostname/icinga-web/web/api/host/filter[AND(HOST_CURRENT_STATE%7C=%7C1)]/countColumn=COL/authkey=MYKEY/json

Any ideas?

**Comment by fdietz** [comment]
The open/closing square bracket seems to be the problem. If I escape them it works.

before:
http://hostname/icinga-web/web/api/host/filter[AND(HOST_CURRENT_STATE%7C=%7C1)]/countColumn=COL/authkey=MYKEY/json

after:
http://hostname/icinga-web/web/api/host/filter%5BAND(HOST_CURRENT_STATE%7C=%7C1)%5D/countColumn=COL/authkey=MYKEY/json

It seems that the path component of an URL doesn't allow the [ or ] characters. It is allowed as part the query though. 

Only the query params are encoded by Faraday. The actual url scheme, host, path fragments should be valid.

**Comment by tubit** [comment]
Hi Frederik,

that looks good. Thanks!

Cheers
Dennis
