### ISSUE TITLE
Do not always re-fetch metrics/targets collection

### ISSUE THREAD

**Issue by fdietz** [fdietz/team_dashboard#6]
Currently, when ever the user selected a source there's a fetch request for the metrics/targets collection. This takes quite a while.

Instead we should fetch each metric only once and keep it in a "pool" to reuse later on. 

Refresh of the collection should happen automatically in the background, preferably without a specific user action.

**Comment by fdietz** [comment]
I've implemented an initial version for it:
https://github.com/fdietz/team_dashboard/commit/3dd6ed5f133fdfa73d4cf92cf62c561bfb2388eb

What's missing is the automatic update refresh of the collection, but this is not that important IMHO.

If it works for everyone, I'll close the ticket.

**Comment by fdietz** [comment]
I assume everything's alright. Closing ticket.

**Comment by luxflux** [comment]
I'm sorry that I didn't answer to this one. Just missed it... It works for me! Thank you!
