### ISSUE TITLE
 Exception Tracker Widget does not work

### ISSUE THREAD

**Issue by niQo** [fdietz/team_dashboard#77]
Errbit widget dos not show anything on a fresh install or on the heroku demo app.

**Comment by fdietz** [comment]
Hi niQo!

which version are you using? Latest master? 

Did you find errors in the log you can post?

Thanks!

**Comment by niQo** [comment]
Hi fdietz, thanks for your answer.

 I'm using latest master.

Nothing special in logs:
Started GET "/api/data_sources/exception_tracker?source=errbit&widget_id=65" for 192.168.127.188 at 2013-04-10 00:27:19 +0200
Processing by Api::DataSourcesController#index as JSON
  Parameters: {"source"=>"errbit", "widget_id"=>"65", "kind"=>"exception_tracker"}
  Widget Load (0.6ms)  SELECT `widgets`.\* FROM `widgets` WHERE `widgets`.`id` = 65 LIMIT 1
Requesting from http://errbit.dev:3000/api/v1/stats/app.json?api_key=9c423a637e9198887b69fd15e41e144f ...
Completed 200 OK in 76ms (Views: 0.6ms | ActiveRecord: 0.0ms)

results from errbit's query:
{"name":"test","last_error_time":"2013-04-09T16:59:30+02:00","unresolved_errors":5}

Perhaps a problem on my installation, I will investigate more.

**Comment by fdietz** [comment]
Hi again,

thanks for the debug information. It shouldn't be a problem in your
installation, since the request is done correctly and the result is parsed
correctly, too.

So, it must a problem in the widget rendering the result. I will look into
it!

Thanks a lot!
Frederik

**Comment by fdietz** [comment]
Fixed! Thanks for your report!
