### ISSUE TITLE
How to get a value from Json array with HTTP Proxy data source ?

### ISSUE THREAD

**Issue by niQo** [fdietz/team_dashboard#79]
how to get Error value from this JSON example ?

{"rows":[
{"key":[2013,4,19],"value":{"Warning":0,"Error":16,"Critical":0,"Alert":0,"Emergency":0}}
]
}

Using "rows.value.Error" as value path does not work.

**Comment by fdietz** [comment]
It is currently not possible to select from arrays. But, there is a pull request almost ready to merge:
https://github.com/fdietz/team_dashboard/pull/73

This will definitly be included in the version 2 release.
