### ISSUE TITLE
Use faraday and provide single place for all HTTP requests

### ISSUE THREAD

**Issue by fdietz** [fdietz/team_dashboard#8]
Use faraday gem and provide a single place for the configuration of all HTTP requests done by web app.

Configuration includes proxy and ssl settings.

It also might happen that we end up with specific options per request

**Comment by luxflux** [comment]
This seems to be done already with `HttpService`, no? What are you missing? I'd like to contribute but I don't see what's missing here :) And the other issues... I tried to dig into Backbone.js, but yeah... Not that easy as I thought :D

**Comment by fdietz** [comment]
Agreed :-)
