### ISSUE TITLE
Close dialog if go to homepage

### ISSUE THREAD

**Issue by Tropicalista** [fdietz/team_dashboard#85]
If I'm on http://team-dashboard.herokuapp.com/dashboards/6403 and open modal and then press back button, when I go to http://team-dashboard.herokuapp.com/dashboards/ the modal should disappear.

I'm not sure how to delete the modal.

Probably this should be done watching the route change?

**Comment by Tropicalista** [comment]
A solution could be:

```
    $scope.$on('$routeChangeStart', function() { 
                dialog.close()
    })
```

on the WidgetEditCtrl controller

**Comment by fdietz** [comment]
Fixed by updating angular-ui modal/dialog library. It solves this in a similar way you propose.

Thanks!
