### ISSUE TITLE
Adding a meter widget using the datapoints source doesn't allow adding further details

### ISSUE THREAD

**Issue by ferrouswheel** [fdietz/team_dashboard#91]
There seems to be a UI issue with adding a meter widget. When I select the datapoints source it doesn't update the dialog to allow the addition of datapoint details

If I manually post a json object, with details for creating a meter using the datapoints source, then it works okay.

Chosing the datapoints source for the number widget does show a dialog with extra details.

Using c0c04e8940

rails 3.2.13
ruby 1.9.3p0

Tried both firefox 21 and chrome 27.0.1453.93

**Comment by fdietz** [comment]
Hi ferrouswheel! I can confirm that it is not working. That's a bug I'll have to look into!

**Comment by chron0** [comment]
It still doesn't seem to work. I've selected datapoints as source and would expect to have a dropdown just like in the number widget where I can choose graphite for example. However, nothing happens UI wise when I select datapoints.
Tested on 0bb0cbb6d83b5192dae2adc652c6a8cf950c276d (that should include the pull request from @averell23) with Ruby 1.9.3p448

**Comment by fdietz** [comment]
Should be working now!
