### ISSUE TITLE
Support minimum value or yaxis resize timeout.

### ISSUE THREAD

**Issue by ferrouswheel** [fdietz/team_dashboard#93]
When accessing a graphite chart with nonNegativeDerivative(metric), the latest timepoint varies on magnitude on each update. It starts at 0, and then increases as there is a greater difference from the last stat. This is an issue when looking at a metric that monotonically increases (like # of uwsgi requests).

This is all fine, but it makes the updating of the graph look weird because the yaxis jumps from having a minimum of 0 to whatever the average throughput is.

e.g,

![screenshot from 2013-06-20 09 57 54](https://f.cloud.github.com/assets/120327/678102/a02249ec-d92b-11e2-9a1d-82776079696c.png)

![screenshot from 2013-06-20 09 58 02](https://f.cloud.github.com/assets/120327/678103/a1a0a796-d92b-11e2-957d-f51786b68ebd.png)

This is a sudden jarring change, and every update it gradually resolves to the upper image again.

Having a timeout on the yaxis adjustment would probably solve this (unless the data is outside the old range, in which case I would expect an immediate change)

**Comment by fdietz** [comment]
I am actually experimenting to drop my render code for graphite and instead use the svg format exposed in more recent versions from graphite. This should also solve your issues.

Here's the issue for you to follow:
https://github.com/fdietz/team_dashboard/issues/80

I'm therefore closing this issue. Please, feel free to reopen in case I'm missing something!

Cheers,
Frederik
